redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :index]

  resources :subs do
    resources :posts, except: [:index]
  end

  

  resource :session, only: [:new, :create, :destory]
end

redditclone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

redditclone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence:true

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub

end

redditclone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, :description, :user_id, presence: true

    belongs_to :moderator,
        foreign_key: :user_id,
        class_name: :User
    
    has_many :posts,
        foreign_key: :sub_id,
        class_name: :Post

    

end

redditclone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6, allow_nil: true}


    after_initialize :ensure_session_token

    attr_reader :password

    has_many :subs,
        foreign_key: :user_id,
        class_name: :Sub

    has_many :posts,
        foreign_key: :author_id,
        class_name: :Post


    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil 
        end
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.generate_session_token
        SecureRandom.base64
    end
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def reset_session_token
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

end

redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token
    end

    def logout
        current_user.reset_session_token if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        @post.sub_id = params[:sub_id]
        if @post.save
            redirect_to sub_post_url([params[:sub_id], @post.id])
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to sub_post_url(@post)
        else
            render :edit
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to subs_url
    end

    def show
        @post = Post.find(params[:id])
        render :show
    end

    private
    def post_params
        params.require(:post).permit(:title, :url, :content)
    end

end

redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ['Invalid Login']
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

    before_action :ensure_logged_in

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update_attributes(subs_param)
            redirect_to sub_url(@sub)
        else
            render :edit
        end
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(subs_param)
        @sub.user_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            render :new
        end
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    private
    def subs_param
        params.require(:sub).permit(:title, :description)
    end
end

redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

redditclone/app/helpers/application_helper.rb
module ApplicationHelper
end

redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

redditclone/app/views/posts/new.html.erb
<h1>Add a new post!</h1>


<form action="<%= sub_posts_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

    <label> Title: 
        <input type="text" name="post[title]">
    </label>

    <label> URL: 
        <input type="text" name="post[url]">
    </label>

    <label> Content: 
        <textarea name="post[content]"> </textarea>
    </label>

    <button>Create</button>

</form>

redditclone/app/views/posts/show.html.erb
<h1>this is post's show page</h1>

<%= @post.title %>

redditclone/app/views/subs/new.html.erb
<h1>Create a Sub!</h1>



<form action="<%= subs_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="title"> Title:
        <input type="text" name="sub[title]">
    </label>

    <label for="description"> Description:
        <input type="text" name="sub[description]">
    </label>

    <button>Create</button>

</form>

redditclone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

redditclone/app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
        Username
        <input type="text" name="user[username]">
    </label>
    <label>
        Password
        <input type="text" name="user[password]">
    </label>
    <button>Sign Up</button>
</form>

redditclone/app/views/users/show.html.erb
<h1><%= @user.username %>'s Info</h1>